### ISSUE TITLE
无法build通过

### ISSUE THREAD

**Issue by gwl7810** [RoderickQiu/wnr#14]
TypeError: appId must be a string
    at Object.init (D:\thunderdownload\wnr-master\node_modules\leancloud-storage\dist\node\init.js:94:21)
    at leanCloudSolution (D:\thunderdownload\wnr-master\main.js:840:12)
    at App.<anonymous> (D:\thunderdownload\wnr-master\main.js:548:5)
    at App.emit (events.js:215:7)
Done in 74.24s.

Terminal will be reused by tasks, press any key to close it.

**Comment by RoderickQiu** [comment]
之所以出现这个问题是因为我们使用dotenv储存了一些敏感信息，没有包括在公开数据库中。
现在已经完成了相关优化，应该是可以在没有这些信息的情况下使用了。你可以再Clone一次并编译。
